# Generated by Django 4.2 on 2024-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
