# Generated by Django 4.2 on 2024-04-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_iris_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
